image: node:12

variables:
  LATEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest

stages:
  - pre-build
  - build
  - deploy

prepare-app:
  stage: pre-build
  artifacts:
    expire_in: 1 year
    paths:
      - build
  cache:
    paths:
      - node_modules
  script:
    - apt-get install libpng-dev -y
    - export CI=false
    - yarn install
    - yarn build
  only:
    - master

build-app:
  stage: build
  image: docker:stable
  dependencies:
    - prepare-app
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $LATEST_IMAGE .
    - docker push $LATEST_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --stack $RANCHER_STACK --service $RANCHER_SERVICE --new-image $LATEST_IMAGE --start-before-stopping
  only:
    - master
